version: "3.3"
services:
  app:
    build:
      context: .
    volumes:
      - .:/core
    ports:
      - 3000:3000
    image: app:react  
    container_name: govinena_redesign
    command: npm start